<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="accounts/**/*.cs" />
    <Compile Remove="official/**/*.cs" />
    <Compile Remove="nightly/**/*.cs" />
    <Compile Remove="codawolf/**/*.cs" />
    <Compile Remove="news/**/*.cs" />
    <Compile Remove="official/**/obj/**/*.cs" />
    <Compile Include="../ManagedMods.cs" Link="ManagedMods.cs" />
  </ItemGroup>
</Project>
