<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../CodaWolfNightlyInstaller.cs" Link="CodaWolfNightlyInstaller.cs" />
    <Compile Include="../../NightlyReleaseSelector.cs" Link="NightlyReleaseSelector.cs" />
    <Compile Include="../../NightlyAtomReleaseReader.cs" Link="NightlyAtomReleaseReader.cs" />
  </ItemGroup>
</Project>
