<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../LauncherModels.cs" Link="LauncherModels.cs" />
    <Compile Include="../../NightlyModIdentity.cs" Link="NightlyModIdentity.cs" />
  </ItemGroup>
</Project>
